services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - db
  frontend:
    build: ./frontend/diary-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/diary-react/:/app/
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: "mongo"
    volumes:
      - "data:/data/db"
    env_file:
      - ./env/mongo.env
    

volumes:
  data:  